name: Pull Requests
on:
  pull_request:
    branches: ["main"]

jobs:
  setupEnvironment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

  checkPRVersion:
    needs: setupEnvironment
    runs-on: ubunti-latest
    steps:
      - name: Check PR version
        shell: bash
        id: check
        run: |
          pr="$(jq -r '.version' < ./package.json)"
          latest="$(git describe --tag --abbrev=0)"
          php -r 'echo"::set-output name=valid::".(version_compare("'"$pr"'","'"$latest"'",">")?"valid":"invalid").PHP_EOL;'

      - name: Step that always run
        shell: bash
        run: |
          echo "PR is ${{ steps.check.outputs.valid }}"
          if [ "${{ steps.check.outputs.valid }}" = "valid" ]
          then
            echo "im valid"
          else
            echo "im invalid"
          fi

      - name: Step that run at valid
        if: steps.check.outputs.valid == 'valid'
        shell: bash
        run: |
          echo "PR is ${{ steps.check.outputs.valid }}"

      - name: Step that run at invalid
        if: steps.check.outputs.valid != 'valid'
        shell: bash
        run: |
          echo "PR is ${{ steps.check.outputs.valid }}"
