name: Pull Requests
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      # - name: Check package.json version
      #   shell: bash
      #   run: |
      #     const pr = `${jq -r '.version' < ./package.json}`.trim();
      #     const latest = `${git describe --tag --abbrev=0}`.trim();
      #     php -r 'if(version_compare("'"$pr"'","'"$latest"'",">")){exit(0);};exit(1);'

      # - name: Step that wont run if not valid
      #   shell: bash
      #   run: |
      #     echo balabala

      - name: Clean Versions
        run: |
          echo "TAG_VERSION=$(echo ${{env.TAG}} | tr -dc '0-9')" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(echo ${{env.PACKAGE}} | tr -dc '0-9')" >> $GITHUB_ENV

      - name:
        run: |
          echo "TAG_NUMBER=$echo$((${{env.TAG_VERSION}} - 0 ))" >> $GITHUB_ENV
          echo "PACKAGE_NUMBER=$echo$((${{env.PACKAGE_VERSION}} - 0 ))" >> $GITHUB_ENV

      - name: Compare Versions
        run: |
          if (( ${{env.PACKAGE_NUMBER}} > ${{env.TAG_NUMBER}} )); then
              echo "PUSH=true" >> "$GITHUB_ENV"

          elif (( ${{env.PACKAGE_NUMBER}} = ${{env.TAG_NUMBER}} )); then
              echo "PUSH=false" >> "$GITHUB_ENV"

          else
              echo "PUSH=false" >> "$GITHUB_ENV"
          fi
