name: Pull Requests
on:
  pull_request:
    branches: ["main"]

jobs:
  setupEnvironment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build

  checkPRVersion:
    needs: setupEnvironment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get package version
        id: package-version
        uses: PostHog/check-package-version@v2

      - name: Compare main and PR package versions
        if: ${{ steps.package-version.outputs.is-new-version }} == 'false'
        run: |
          echo "Please, update the package.json version."
          exit 1
